[project]
name = "corona-pcap-processor"
version = "0.1.0"
description = "BACnet network traffic analyzer for PCAP files"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-libpcap>=0.5.2",
    "click>=8.1.8",
]
